# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  config:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.setName.outputs.name }}
      deployTag: ${{ steps.setTag.outputs.deployTag }}
      cr_name: ${{ steps.setCRName.outputs.cr_name}}
      sp_id: ${{ steps.setSpId.outputs.sp_id}}
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2
    - name: 'Set Name'
      id: setName
      run: |
        NAME=$(jq -r '.["parameters"]["name"]["value"]' infrastructure/params-production.json)
        echo "::set-output name=name::${NAME//'%'/'%25'}"
    - name: 'Set Container Registry Name'
      id: setCRName
      run: |
        CR_NAME=$(az acr list -g ${{ secrets.AZURE_RG }} --query [0].name -o tsv)
        echo "::set-output name=cr_name::${CR_NAME//'-'/''}"

    - name: 'Set Deploy Tag Name'
      id: setTag
      run: |
        DEPLOY_TAG=$(git describe --tags --always HEAD)
        echo "::set-output name=deployTag::${DEPLOY_TAG}"


  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ config ]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - uses: azure/docker-login@v1
      name: 'Login to Azure Container Registry'
      with:
        login-server: ${{ needs.config.outputs.cr_name }}.azurecr.io
        username: ${{fromJSON(secrets.AZURE_CREDENTIALS).clientId}}
        password: ${{fromJSON(secrets.AZURE_CREDENTIALS).clientSecret}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      with:
        use: true

    - name: Build and Push App
      id: docker_build
      uses: docker/build-push-action@v2.6.1
      with:
        push: true
        target: app
        tags: ${{ needs.config.outputs.cr_name }}.azurecr.io/${{ needs.config.outputs.name }}:${{ needs.config.outputs.deployTag }}
        cache-from: type=registry,ref=${{ needs.config.outputs.cr_name }}.azurecr.io/${{ needs.config.outputs.name }}:buildcache
        cache-to: type=registry,ref=${{ needs.config.outputs.cr_name }}.azurecr.io/${{ needs.config.outputs.name }}:buildcache,mode=max
    
    - name: Export assets
      id: export_assets
      uses: docker/build-push-action@v2.6.1
      with:
        push: false
        target: static
        cache-from: type=registry,ref=${{ needs.config.outputs.cr_name }}.azurecr.io/${{ needs.config.outputs.name }}:buildcache
        outputs: type=local,dest=static
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Store Assets
      run: |
        STORAGE_ACCOUNT_NAME=$(az storage account list -g ${{ secrets.AZURE_RG }} --query [0].name -o tsv)
        EXPIRY=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
        SAS_TOKEN="$(az storage container generate-sas -n assets --as-user --auth-mode login --expiry $EXPIRY --account-name $STORAGE_ACCOUNT_NAME)"
        ASSETS_URL="$(az storage account list -g ${{ secrets.AZURE_RG }} --query [0].primaryEndpoints.blob -o tsv)/assets?${SAS_TOKEN}"
        azcopy copy static $ASSETS_URL
      

  deploy:
    runs-on: ubuntu-latest
    needs:
    - build
    - config
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v2
      
      - name: 'Deploy Infrastructure'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: infrastructure/startup-stack.bicep
          parameters: "infrastructure/params-production.json dbPassword=${{ secrets.DB_PASSWORD }} deployedTag=${{ needs.config.outputs.deployTag }}"
        


